### ISSUE TITLE
add continuous integration for validation

### ISSUE THREAD

**Issue by vippolit** [MechanicalVentilatorMilano/MVMAnalysis#26]
it would be nice if, after every push, validation plots would be produced (maybe with the web interface being developed by Silvia, @sviel ?) based on some reference (simplified) dataset we could make available somewhere

**Comment by sviel** [comment]
I agree!  CI can be setup on GitHub under "Actions", but I haven't tried it yet

To test combine.py the algorithm would need a way to access small MVM and simulator data files, either by including them in the repo (easier but takes space), or making them available for download on each test

**Comment by sviel** [comment]
started in #27

**Comment by vippolit** [comment]
> To test combine.py the algorithm would need a way to access small MVM and simulator data files, either by including them in the repo (easier but takes space), or making them available for download on each test

I think we can use the latter, maybe with github secrets to store a service account token (which I suppose exist as they do in gitlab)

**Comment by sviel** [comment]
CI was implemented in #27
